steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - apps_builder_function
  - --entry-point=main_http
  - --source=.
  - --trigger-http
  - --runtime=python39
  - --allow-unauthenticated
  - --memory=1024MB
  - --region=europe-west1